# Based on https://github.com/withastro/astro/blob/main/.devcontainer/Dockerfile
FROM mcr.microsoft.com/devcontainers/javascript-node:0-18

# Enable corepack for yarn
RUN corepack enable

COPY welcome-message.txt /usr/local/etc/vscode-dev-containers/first-run-notice.txt